name: Node Continuous Integration

on:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - main
    
jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm i
      # - name: Run test
      #   run: npm test
      #   env:
      #     DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      #     DB_HOST: ${{ secrets.DB_HOST }}
      #     DB_PORT: ${{ secrets.DB_PORT }}
      - run: npm run build
      - run: ls -al
      - run: pwd
      - run: mkdir -p ./build/src/orm
      - name: test secrets val
        env:
          TEST_VAL: ${{secrets.TEST_VAL}}
        run: echo $TEST_VAL
      - name: run model gen
        env: 
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: npx typeorm-model-generator -h $DB_HOST -d chatbot_system -p $DB_PORT -u root -x $DB_PASSWORD -e mariadb -o "./build/src/orm"
      - name: Fuck model gen not work
        run: mkdir -p build/src &&  cp -r src/orm build/src/orm
      - name: Zip files
        run: tar -cvf deploy.tar ./build/
      # https://stackoverflow.com/a/61236896/7270469
      # https://github.com/appleboy/scp-action
      - name: Deploy update file
        uses: appleboy/scp-action@master
        with: 
          host: ${{ secrets.LIVE_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "deploy.tar"
          target: ${{ secrets.DEPLOY_DIR }}

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIVE_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            mkdir -p ./deploy && tar -xvf deploy.tar -C ./deploy
            rm deploy.tar
            mkdir -p $HOME/KangnamShuttle4.0/main_container/kws1/build
            mv deploy/build/* $HOME/KangnamShuttle4.0/main_container/kws1/build/
            cd $HOME/KangnamShuttle4.0/main_container/kws1
            docker-compose build
            docker-compose up -d

